### ISSUE TITLE
플러그인 설정이 안되네요.

### ISSUE THREAD

**Issue by overjsw** [OrigamiDream/homebridge-daelim-smarthome#106]
오랫동안 잘 써왔는데 갑자기 로그인이 안되네요.
예상되는 문제로는 홈브릿지 다른 플러그인을 설치를 하다가 문제 있는 상태로 2일이 지났는데,
홈브릿지가 2일 내내 재시작을 하고 있어서
아마도 계속 로그인 시도를 했을 것 같은데 이로 인해서 서버가 절 차단한건 아닌가 싶네요.

[homebridge-daelim-smarthome.log.txt](https://github.com/user-attachments/files/16735090/homebridge-daelim-smarthome.log.txt)

**Comment by OrigamiDream** [comment]
Homebridge의 2.0 메이저 업데이트를 위한 물밑작업으로 인해 몇몇 의존성이 호환되지 않고, Google 측에서 푸시 알람용 GCM 시스템을 2024년 6월 24일자로 종료해버려서, 생각보다 큰 업데이트가 되어야 할 것 같습니다.

저도 그동안 재시작을 한 적이 없다보니 지금까지 몰랐네요.
작업에는 시간이 조금 걸릴 것 같고, 수정되는대로 추가 이슈 달겠습니다.

**Comment by overjsw** [comment]
> @overjsw v1.4.4-beta.0 버전을 배포했습니다. 설치하시고 문제가 해결되었는지 확인 부탁드립니다.

문제가 해결되었습니다. 감사합니다.
