### ISSUE TITLE
엘레베이터 사용불가

### ISSUE THREAD

**Issue by HJcom** [OrigamiDream/homebridge-daelim-smarthome#107]
안녕하세요
기존에 1.4.0 버전 사용 중이였다가 이번에 오류로 인해 1.4.4-beta.0 버전으로 올렸는데
사용 중이던 엘레베이터 악세사리가 뜨질 않네요 ㅠ
로그 첨부 합니다 
[daelimlog.txt](https://github.com/user-attachments/files/16755295/daelimlog.txt)

**Comment by OrigamiDream** [comment]
@HJcom 확인을 위해 거주하고 계시는 아파트 이름이 필요합니다. hello@origamidream.me 여기로 아파트 이름만 적어서 보내주시면 확인해보겠습니다.

**Comment by OrigamiDream** [comment]
@HJcom 보내주신 아파트 확인 결과 엘레베이터 호출이 해당 아파트에서 비활성화 되어 있는 것으로 나와 있습니다.

이 경우 e편한세상 공식 앱에서도 엘레베이터 메뉴가 사라졌을 거라, 점검 등의 사유로 잠시 막아둔 것이 아니라면 아파트 자체에서 엘레베이터 호출 기능을 없앤 것으로 봐야 합니다.

**Comment by HJcom** [comment]
월패드에서 호출 기능은 지금도 사용 가능한데 아파트 서버에서 뭔가 막았나보네요 ㅠ ha에서 엘베 호출만 해보려고 ew11붙여서 rs485 패킷 호출 해봐도 반응 없더니 아파트 자체 에서 뭔가 막아놓아서 그런가보네요 ㅠ 감사 합니다 ㅠ
