### ISSUE TITLE
각방 보일러 인식 여부

### ISSUE THREAD

**Issue by HJcom** [OrigamiDream/homebridge-daelim-smarthome#55]
안녕하세요 먼저 플러그인 만들어 주셔서 정말 감사 합니다.
다름이 아니라 거실을 제외한 각방 보일러 액세서리가 생성 되질 않아 이렇게 보냅니다.
매번 엘리베이터 , 조명1,2 , 가스 , 거실 히터 이렇게만 나오다가
디버깅 모드 변경이후 다시 재시작해보니 방2 히터 액세서리가 다시 나오긴 하네요
나머지 방 1,방3 히터 액세서리는 어떻게 해야 나올까요?
도움 부탁 드립니다.
[homebridge.log.txt](https://github.com/OrigamiDream/homebridge-daelim-smarthome/files/10128878/homebridge.log.txt)

**Comment by HJcom** [comment]
추가 문제가 발생 해서 남깁니다.ㅜ
대림플러그인을 설치 하고 홈킷과 홈브릿지를 연동 시키면 액세서리 준수범위 문제로 등록이 안됩니다 
반대로 대림 플러그인을 설치 안하고 홈킷에 홈브릿지 연동 이후 플러그인을 설치시 액세서리가 없다고 나옵니다 ㅜ
[homebridge.log (2).txt](https://github.com/OrigamiDream/homebridge-daelim-smarthome/files/10133711/homebridge.log.2.txt)

**Comment by OrigamiDream** [comment]
2번 문제는 플러그인 재설치 과정에서 Config 설정이 누락되어서 그런거 같습니다. 플러그인 설정에 가셔서 "재설정" 후 다시 설정해주세요.
1번 문제는 일단 보이는대로 수정해 보았는데, 플러그인 목록에서 펜치 모양 아이콘 클릭하시고 "이전 버전 설치"에서 "v1.3.8-beta.0" 를 설치하셔서 어떻게 변화하는지 알려주시겠어요?

**Comment by HJcom** [comment]
1.3.8-beta.0 설치 이후 거실과 방1 보일러 액세서리가 올라왔습니다
방2,3은 안올라오네요 
홈킷에 홈브릿지 액세서리 추가 하려고 하면 액세서리 준수 범위가 벗어났다고 나오고 등록이 안됩니다 
[homebridge.log (3).txt](https://github.com/OrigamiDream/homebridge-daelim-smarthome/files/10138056/homebridge.log.3.txt)

**Comment by OrigamiDream** [comment]
문제 수정한 v1.3.8-beta.1 을 배포하였습니다. 테스트 부탁드립니다.

**Comment by HJcom** [comment]
안녕하세요 v1.3.8-beta.1 테스트 로그 첨부 합니다 
히터 방 2,3이 아직 안올라 옵니다 ㅜ
QR코드로 홈킷에 액세서리 추가시 여전히 액세서리 준수범위 경고 뜨고 홈브릿지 등록이 안됩니다 
이건 원인이 뭘까요 ㅠ

괜히 짐을 안겨 드린것 같아 죄송스럽습니다 ㅠㅠ
축구 즐겁게 보시고 좋은 주말 되시길 바랍니다 :)

-----Original Message-----

**Comment by OrigamiDream** [comment]
문제 수정한 v1.3.8-beta.2 를 배포하였습니다.
**홈브릿지에 등록된 액세서리를 초기화하신 후** 플러그인을 재설치해 주시기 바랍니다.

**Comment by HJcom** [comment]
v1.3.8-beta.2 버전 설치 결과 보냅니다
액세서리 초기화 이후 홈킷에 브릿지 등록 가능해졌습니다.
다만 방1,2,3 히터 악세사리가 올라오지 않았습니다 ㅜ
매번 수정 해주셔서 정말 감사 합니다
 
-----Original Message-----

**Comment by OrigamiDream** [comment]
문제 수정한 v1.3.8-beta.3 을 배포하였습니다. 테스트 부탁드립니다.

**Comment by HJcom** [comment]
v1.3.8-beta.3 테스트 결과 모든 악세사리가 정상적으로 등록 됩니다
그런데 홈킷에 브릿지 등록시 액세서리 준수범위 경고 떠서 연결이 안됩니다 ㅜ

-----Original Message-----

**Comment by OrigamiDream** [comment]
v1.3.8-beta.4 을 배포하였습니다. 테스트 부탁드립니다.

**Comment by HJcom** [comment]
홈브릿지 액세서리 초기화 이후 v1.3.8-beta.4 설치 해봤는데 여전히 액세서리 준수범위 때문에 홈킷에 
붙일수가 없습니다.
여러번 초기화 해보고 재부팅 해보면 홈브릿지 액세서리는 다 올라오는데 홈킷에는 준수범위가 뜹니다 ㅜ
-----Original Message-----

**Comment by OrigamiDream** [comment]
homebridge 로그에는 더 이상 이상 징후가 나타나지 않아서 이제는 뭐가 문제인지 판단하기 어렵네요.
제가 직접 계정을 받아서 확인하고 작업하는 것이 제일 확실하기에, 혹시라도 괜찮으시다면 계정 정보를 받을 수 있을까요?

저는 작업 후 받은 계정 정보는 메일 기록과 함께 파기할 예정이고, 추가적으로 비밀번호는 대림 스마트홈 앱에서 변경하실 수 있습니다.
또한 생활에 지장이 가지 않도록 제가 직접 기기를 조작하는 일은 최대한 없게끔 하겠다고 약속드립니다.

괜찮으시다면 제 이메일 [feuds_ebb.0c@icloud.com](mailto:feuds_ebb.0c@icloud.com)로 보내주시면 감사하겠습니다.

**Comment by OrigamiDream** [comment]
v1.3.8-beta.5 를 배포하였습니다. 홈브릿지 액세서리를 반드시 초기화 하신 후 테스트 부탁드립니다.

**Comment by HJcom** [comment]
설정에 가서 재설정해봐도 config 값을 불러오질 못하는 것 같습니다 ㅠ

-----Original Message-----

**Comment by OrigamiDream** [comment]
초기화 중간에 뭔가 깨졌나본데요, 플러그인을 삭제하고 액세서리 초기화 후 재설치해보세요
