### ISSUE TITLE
Heat Exchanger and System Air Conditioning for Additional Support Door

### ISSUE THREAD

**Issue by harwin1** [OrigamiDream/homebridge-daelim-smarthome#75]
전열교환기 및 시스템 에어컨 추가 기능에 대해 지원 가능한지 물어봅니다.. 현재 앱에서는 조작 가능한 상태입니다. ![image](https://user-images.githubusercontent.com/87955512/218570098-0d948969-37ad-4c8a-9780-c3299a40d069.png)
![image](https://user-images.githubusercontent.com/87955512/218570135-bca42c76-d04a-46fc-b1f3-c0fcdd59d530.png)

**Comment by OrigamiDream** [comment]
환기 및 에어컨에 대한 변경점이 `v1.4.1-beta.4` 로 배포되었습니다.
제가 거주하는 아파트에서는 환기 및 에어컨에 대한 원격 조작이 불가능해 리버싱 과정에서 찾은 프로토콜을 따라 만들었습니다.
배포 할 때 까지 문제점이 발견되지 않아야 합니다만, 저는 확인을 할 수 있는 환경이 아닙니다.
따라서 저는 @harwin1 님이 이 점에서 도움을 주신다면 감사하겠습니다.

다음의 QA를 시도해주시고, 관련 화면을 스크린샷(혹은 영상)으로 찍어 보내주시면 동작 확인에 도움이 되겠습니다.

### 환기
1. 홈 앱) 환기 액세서리가 존재하는지 (액세서리 이름은 "환기"로 표시)
2. 홈 앱) 환기가 꺼져 있는 상태에서 액세서리 아이콘을 눌러서 잘 켜지는지
3. 홈 앱) 환기 액세서리 아이콘을 길게 눌러 상세 페이지를 띄운 상태에서 슬라이드가 보이는 경우 - 환기 풍량 조절 가능 단지
    1. 환기가 꺼져 있는 상태에서 슬라이드 바(환기 강도)를 중간에 위치(중풍)하게 하면 환기가 켜지는지
    2. 3.i.를 수행한 상태에서 슬라이드 바를 맨 위에 위치(중풍 → 강풍)하면 실제 환기 강도가 강해지는지
4. 홈 앱) 환기가 켜져 있는 상태에서 액세서리 아이콘을 눌러서 잘 종료되는지
5. 집 공간) 환기 활성화 스위치를 눌러 켰을 때, 홈 앱에서도 같이 활성화가 되는지
6. 집 공간) 환기 활성화 스위치를 눌러 껐을 때, 홈 앱에서도 같이 종료가 되는지

### 에어컨
에어컨은 기본적으로 히터와 동작이 동일합니다.

1. 홈 앱) 에어컨 액세서리가 실제 개수만큼 존재하는지 (아마 이름은 거실, 침실1, 침실2,  침실3으로 표시될겁니다)
2. 홈 앱) 에어컨이 꺼져 있는 상태에서 현재 온도가 표시되는지
3. 홈 앱) 에어컨이 꺼져 있는 상태에서 액세서리 아이콘을 눌러서 잘 활성화 되는지
3. 홈 앱) 에어컨 액세서리 아이콘을 길게 눌러 상세 페이지를 띄운 상태에서
    1. 에어컨이 꺼져 있는 상태에서 하단 전원 모양 버튼을 누르면 조절 가능한 바가 나타나는지
    2. 에어컨이 켜져 있는 상태에서 설정 온도를 조절하면 설정한 온도로 표기되는것이 유지되는지 (이전 온도 설정으로 롤백되는 등의 일이 없게끔)
4. 홈 앱) 현재 온도보다 설정한 온도가 낮거나 같으면 냉방 중 또는 그러한 의미의 단어나 문장이 보여지는지
5. 홈 앱) 현재 온도보다 설정한 온도가 높으면 대기 중 또는 그러한 의미의 단어나 문장이 보여지는지
6. 집 공간) 에어컨을 스위치/리모컨을 눌러 켰을 때, 홈 앱에서도 같이 활성화가 되는지
7. 집 공간) 에어컨을 스위치/리모컨을 이용해 온도를 조절했을 때, 홈 앱에서도 "설정 온도"가 반영되는지
8. 집 공간) 에어컨에 표기되는 (만약 존재한다면) 온도가 홈 앱에서도 동일하게 혹은 비슷하게 반영되어 나타나는지
9. 집 공간) 에어컨을 스위치/리모컨을 눌러 종료했을 때, 홈 앱에서도 꺼짐 상태로 바뀌는지

위 모든 조건이 잘 동작함이 확인되면 정식으로 배포할 예정입니다.

이외에 홈브릿지 내의 콘솔에서 심각한 문제가 발생하는 경우, [문제 해결 방법](https://github.com/OrigamiDream/homebridge-daelim-smarthome/blob/master/TROUBLESHOOTING.md)에 따라 로그를 보내주시고, 고급 설정에서 문제가 발생하는 액세서리를 업데이트를 통해 문제가 해결될 때 까지 비활성화해 주시면 되겠습니다.

**Comment by harwin1** [comment]
아직 입주 전이라 입주 청소 할때 등 시간날때 가서 테스트 해보고 결과 알려드리겠습니다. 계정 정보가 필요하신 경우라면 알려드리겠습니다. 입주 전이라 편하게 조작 해보셔도 무방합니다.

**Comment by OrigamiDream** [comment]
계정 정보를 받으면 테스트 진행이 정말로 편해지는것은 사실이지만,
본래 그 계정을 사용하기 위해서는 해당 호실에서 누군가가 월패드 인증 정보를 180초 내로 알려주어야합니다.

대신 이러한 실시간성을 극복할 수 있는 방법이 있습니다.
먼저 홈브릿지를 개인적으로 설치하셔서, 플러그인 설치 후 계정정보를 입력하여 월패드 인증까지 마치신 경우
그 계정을 Smart Home 2.0 앱에 다시 인증시키지 않는 한 제가 테스트를 할 때에는 추가적인 월패드 인증을 거치지 않아도 됩니다.
(인증 정보가 계정 아이디를 시드로 해싱되기 때문)

되도록이면 이 과정을 거치신 후, 계정 정보를 제 이메일 [feuds_ebb.0c@icloud.com](mailto:feuds_ebb.0c@icloud.com)로 보내주시면 감사드리겠습니다.

**Comment by OrigamiDream** [comment]
@harwin1 
에어컨 및 3단계 조절 전등 관련 변경사항이 `v1.4.1-beta.5`에 배포되었습니다.

에어컨의 경우 서버에서 현재 온도 및 설정 온도를 보내주지 않는 문제를 상정하게끔 수정되었습니다.
3단계 조절 전등 (거실)의 경우 서버 측에서 현 전등 밝기를 보내주지 않기 때문에, 밝기 조절 슬라이더가 비활성화되고 일반 ON/OFF 전등처럼 동작합니다.

이외에 원격으로 테스트를 진행할 수 있는 항목들(홈 앱, Homebridge에서 조작 등)은 모두 테스트되었으며,
추후에 해당 집 내에서 직접 물리적으로 기기를 조작할 경우 홈 앱에 어떻게 반영되는지만 확인해주시면 됩니다.
확인해보시고 잘 동작된다고 말씀해주시면 정식 배포할 예정입니다.

**Comment by harwin1** [comment]
안녕하세요, 지금 수정해주신 베타 버전 테스트를 위해 잠시 일산어반스카이에 와있습니다. 전에 말씀하신 거실 조명 (3단계 ) 밝기는
상태 서버로부터 상태를 보내주지 않아서 일반 on/off 스위치로 작동 하신다 했는데 월패드에서 거실 조명 밝기를 바꾸면 Smart
Home2.0 앱에 거실 조명 밝기가 업데이트 되는데 확인 부탁드려요




2023년 2월 21일 (화) 00:10, OrigamiDream ***@***.***>님이 작성:

**Comment by OrigamiDream** [comment]
1단계 3단계만 표기되고 2단계는 안되지 않던가요?

**Comment by harwin1** [comment]
방금전 보낸 메일 밑에 영상 있어요 확인부탁드려요


2023년 2월 21일 (화) 20:58, OrigamiDream ***@***.***>님이 작성:

**Comment by OrigamiDream** [comment]
이건 깃허브 통해서 오는 메일이라 첨부파일 전달이 안됩니다.
[feuds_ebb.0c@icloud.com](mailto:feuds_ebb.0c@icloud.com) 로 보내주세요

**Comment by OrigamiDream** [comment]
메일 전달이 안 됐나 싶어 여기로 다시 연락드립니다

사용하시는 홈브릿지에서 DEBUG 모드를 활성화하신 뒤 (홈브릿지 설정에 있습니다)
방금 영상 찍으신 것 처럼 월패드/스위치를 직접 여러 단계별로 조절하시고
홈브릿지에 나타난 DEBUG (짙은 회색) 메세지들을 복사해서 보내주시겠어요?

**Comment by OrigamiDream** [comment]
@harwin1 
3단계 전등 조절 관련 업데이트가 `v1.4.1-beta.6`에 배포되었습니다.

말씀해주신 입차 및 현관문 관련 알람 설정을 확인해 봤으나 알람이 모두 활성화되어 있었으며, 
따로 이러한 알람을 받지 못하는 아파트가 아니었습니다.

따라서 사용자분 홈 앱에서 해당 액세서리의 알람이 꺼져 있지 않은지 확인 부탁드립니다.

**Comment by OrigamiDream** [comment]
혹시 확인 해보셨나요?

**Comment by harwin1** [comment]
이사를 일요일에 가서 말이죠.. 제가 홈킷 허브가 없어 이사가서 인터넷 망을 구성해봐야 테스트 될거 같은데 일단 오늘 가능하면 테스트 해볼게요

**Comment by OrigamiDream** [comment]
아하 알겠습니다. 그럼 시간 나실 때 확인하셔서 어떤지 알려주세용

**Comment by harwin1** [comment]
잘 동작하는거 같습니다 ㅎㅎ 거실 밝기도 잘 됩니다 ㅎ

**Comment by OrigamiDream** [comment]
The changes have been merged into `master` branch
