### ISSUE TITLE
 Establishing connection failed due to semaphore from ui-server

### ISSUE THREAD

**Issue by jihangshin** [OrigamiDream/homebridge-daelim-smarthome#81]
안녕하세요 

다음과 같은 에러는 어떤 경우에 발생하는지 문의 드립니다. 
현재 기기 원격 조정이 안되는 상황입니다. 

[DL E&C] Establishing connection failed due to semaphore from ui-server

**Comment by OrigamiDream** [comment]
플러그인 설정 중 비정상 종료로 인해 발생한 문제로 보입니다.
우선 홈브릿지를 재시작하여 해결이 되는지 확인해보시고, 그래도 안된다면 홈브릿지에서 터미널을 실행하여 다음의 명령어를 시도해보세요.
```bash
rm daelim-semaphore
```

**Comment by jihangshin** [comment]
혹시 몰라 지금 스마트홈2.0 어플 로그인을 시도해봤는데, 로그인이 되지 않네요. 
스마트홈 서버에 이상이 있을 경우에도 해당 에러가 발생하는지요?

**Comment by OrigamiDream** [comment]
플러그인 설정을 연 첫 10초 동안은 홈브릿지쪽 연결이 중단됩니다.
따라서 아파트 서버가 중지된 상태라면 계속 연결을 재시도할 것이고, 이 상태에서 플러그인 설정을 열면 10초간 홈브릿지 로그에 해당 오류가 반복적으로 표기될 가능성이 있습니다.
아파트 서버는 아파트별로 따로 존재하기 때문에 제 쪽에서는 서버가 다운된 여부를 알 수 없지만 로그를 확인해보시고 해당 오류 메세지와 별개로 연결을 계속 재시도하는 메세지가 있는지 확인해보세요

**Comment by OrigamiDream** [comment]
문제가 해결되었나요?

**Comment by jihangshin** [comment]
단지 내 서버가 문제가 있는지, 아직도 로그인이 되고 있지 않네요. 

혹시 신촌1단지 서버 담당자 연락처 아실까요?

**Comment by OrigamiDream** [comment]
스마트홈 앱에서도 로그인이 안 되는 상태라면 기다려볼 수 밖에 없겠네요.. 담당자 연락처는 모릅니다

**Comment by jihangshin** [comment]
확인 감사합니다 ^^ 관리사무소에 전화 한번 해봐야겠네요 ㅋ
