### ISSUE TITLE
Device MQTT Operation

### ISSUE THREAD

**Issue by lunDreame** [OrigamiDream/homebridge-daelim-smarthome#90]
Is it possible to add functions to operate DL E&C devices with MQTT? If additional MQTT function can be added, I wonder if it is possible to add the energy consumption function of the SmartHome 2.0 app. Homekit has no energy-related accessories, but MQTT allows you to publish your power status and work with MQTT Topics on other platforms for greater scalability.

**Comment by OrigamiDream** [comment]
Are you talking about this?

![IMG_4AD8A637DFF1-1](https://github.com/OrigamiDream/homebridge-daelim-smarthome/assets/5837620/ee719c37-6a4b-413f-8432-d211cec24122)

**Comment by iluna8** [comment]
yes

**Comment by OrigamiDream** [comment]
I'll consider your suggestion later when I have some free time.

**Comment by iluna8** [comment]
오랜만에 댓글 남겨 봅니다.. 시간 나실때 고려 부탁드립니다..ㅠ 홈킷에서 에너지 사용량을 지원을 안해 아쉬울 따름이네요..
혹시 Eve를 통해 전력량을 보내면 HomeAssistant로 끌어올 수도 있을거 같습니다. hombridge-mqttthing 플러그인 소켓과 별개로 사용량을 보내면 홈 앱에서는 소켓만 나타나지만 Eve 앱에서는 전력량도 같이 표시되더라고요.
